swagger: "2.0"
info:
  description: "API Documentation"
  title: "API"
  version: "1.0.0"
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/x-www-form-urlencoded
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /items:
    $ref: 'api/swagger/paths/items.yaml#/items'

definitions:
  Items:
    $ref: "api/swagger/models/Items.yaml"
  ErrorResponse:
    $ref: "api/swagger/models/ErrorResponse.yaml"